### ISSUE TITLE
Why does the IdGenerator work?

### ISSUE THREAD

**Issue by LiveNathan** [schauder/talk-migrate-jpa-to-spring-data-jdbc#1]
Hi Jens! Thanks for your talk at Spring IO and this demo project. I was struggling all day yesterday just two get two JDBC entities linked and your demo finally helped me understand it.

There's one thing I don't understand. If I write a test directly against the repository where I attempt to save an entity with a null id, it fails. But, if I change the SQL from `id BIGINT` to `id SERIAL`, it works. This tells me that my test, using Testcontainers, written against the repo skips the beforeConvertCallback EventListener. So I'm wondering, how does the IdGenerator work? Is there some agreement between the database and us, the client, that say, "Hey, we're handling the ids now."?

I guess I'm also wondering how to write a test to make sure my IdGenerator implementation will work correctly, but I haven't even tried, yet.

https://github.com/schauder/talk-migrate-jpa-to-spring-data-jdbc/blob/2dc1923572d7213822cc30821a8074c0bc99ec09/JPA-JDBC-migration/src/main/java/de/schauderhaft/jpajdbcmigration/IdGenerator.java#L9

For context, here's the test I mentioned:

```java
@Testcontainers
@Tag("database")
@DataJdbcTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class JdbcInterviewRepositoryTest {
    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Autowired
    JdbcInterviewRepository interviewRepository;

    @Test
    void connectionEstablished() {
        assertThat(postgres.isCreated()).isTrue();
        assertThat(postgres.isRunning()).isTrue();
    }

    @Test
    void canReadAndWriteInterviewDbo() {
        IntervieweeDbo intervieweeDbo = new IntervieweeDbo(null, "name",
                "jobTitle", FollowUpChannel.EMAIL, "email");

        InterviewDbo interviewDbo = new InterviewDbo(null, intervieweeDbo,
                DateFactory.getDate(), "urlAudio", "urlYt", "transcript");

        InterviewDbo savedDbo = interviewRepository.save(interviewDbo);

        assertThat(savedDbo.id()).isNotNull();

        Optional<InterviewDbo> foundDbo = interviewRepository.findById(savedDbo.id());

        assertThat(foundDbo)
                .isPresent()
                .get()
                .extracting(InterviewDbo::responseTimestamp)
                .isEqualTo(interviewDbo.responseTimestamp());

        boolean exists = interviewRepository.existsByResponseTimestamp(interviewDbo.responseTimestamp());

        assertThat(exists).isTrue();
    }

}
```

**Comment by schauder** [comment]
> So I'm wondering, how does the IdGenerator work? Is there some agreement between the database and us, the client, that say, "Hey, we're handling the ids now."?

The "agreement" between Spring Data JDBC and the database is pretty one sided. 
Spring Data JDBC by default will not provide the id during the insert and assumes that the database + its driver generates the id and returns it. Spring Data JDBC will actually fail when the id is not set after inserting a record.
Id generation is an exception to that default. 
First an entity is inspected and by detecting that the id is `null` (simplified) it is decided that an insert is in order.
But then the `BeforeConvertCallback` implementations are called and if after this the id is not null that value will be used during the insert.

You can find more details about this in [How to use custom ID generation](https://spring.io/blog/2021/09/09/spring-data-jdbc-how-to-use-custom-id-generation).

> I guess I'm also wondering how to write a test to make sure my IdGenerator implementation will work correctly, but I haven't even tried, yet.

I'd say there are two parts of a working id generator:

1. It needs to do the right thing when called. 
    You can test that by a unit test calling the id generator and inspecting the returned entity.
2. It needs to properly get registered as an `ApplicationEventListener`.
    I guess you could verify this by either inspecting the `ApplicationContext`, or by running a full integration test as you seem to already do.
    
I would need to have a look at your code in order to understand what is going on in your specific scenario.
But that is really out of scope for an issue on this project. I'm therefore going to close this one.

If you have further usage questions, please ask those on Stackoverflow tagged with `spring-data-jdbc`.
If you think you found a bug, a possible improvement or similar for Spring Data JDBC, please create a ticket on https://github.com/spring-projects/spring-data-relational/issues 

One more side note: You seem to query by timestamp. That is a pretty brittle operation, because since databases often truncate timestamps equality comparisons are quick to fail in unexpected ways.

**Comment by LiveNathan** [comment]
Wow, Jens, thanks so much for the detailed response. Ok, I will move future conversations to Stackoverflow. And thanks for the note on timestamp. I did not consider that.
